const Colors = {
  light: {
    text: '#11181C',
    background: '#fff',
    tint: '#0a7ea4',
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: '#0a7ea4',
    headerBackground: '#fff',
    headerText: '#000',
    inputBackground: '#fff',
    inputBorder: '#ccc',
    deviceItemBackground: '#fff',
    deviceItemBorder: '#ccc',
    selectedDeviceBackground: '#e0e0e0',
    deviceDescription: '#777',
    saveButton: '#0a7ea4',
  },
  dark: {
    text: '#ECEDEE',
    background: '#151718',
    tint: '#fff',
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: '#fff',
    headerBackground: '#151718',
    headerText: '#fff',
    inputBackground: '#222',
    inputBorder: '#555',
    deviceItemBackground: '#222',
    deviceItemBorder: '#555',
    selectedDeviceBackground: '#333',
    deviceDescription: '#ccc',
    saveButton: '#fff',
  },
};

export default Colors;
